-- Enable pgvector extension (must run before any tables that use vector type)
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable pg_trgm for full-text search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- This migration is auto-generated by Prisma.
-- The full schema DDL will be generated when you run:
--   prisma migrate dev
-- This file exists to ensure pgvector is enabled first.
