export const FEATURE_FLAGS = {
  AI_ASSISTANT: 'FEATURE_AI_ASSISTANT',
  BANK_INTEGRATION: 'FEATURE_BANK_INTEGRATION',
  MARKETPLACE_SYNC: 'FEATURE_MARKETPLACE_SYNC',
  EMAIL_MARKETING: 'FEATURE_EMAIL_MARKETING',
  TELEGRAM: 'FEATURE_TELEGRAM',
  CALENDAR: 'FEATURE_CALENDAR',
  MULTI_LOCATION: 'FEATURE_MULTI_LOCATION',
  ECOMMERCE_API: 'FEATURE_ECOMMERCE_API',
} as const;

export type FeatureFlagKey = typeof FEATURE_FLAGS[keyof typeof FEATURE_FLAGS];
